# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EvolutionParametersDialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EvolutionParametersDialog(object):
	def setupUi(self, EvolutionParametersDialog):
		EvolutionParametersDialog.setObjectName("EvolutionParametersDialog")
		EvolutionParametersDialog.resize(264, 280)
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(EvolutionParametersDialog)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.groupBox = QtWidgets.QGroupBox(EvolutionParametersDialog)
		self.groupBox.setObjectName("groupBox")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.labelParentCount = QtWidgets.QLabel(self.groupBox)
		self.labelParentCount.setObjectName("labelParentCount")
		self.horizontalLayout.addWidget(self.labelParentCount)
		spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem)
		self.spinBoxParentCount = QtWidgets.QSpinBox(self.groupBox)
		self.spinBoxParentCount.setMinimum(2)
		self.spinBoxParentCount.setProperty("value", 4)
		self.spinBoxParentCount.setObjectName("spinBoxParentCount")
		self.horizontalLayout.addWidget(self.spinBoxParentCount)
		self.verticalLayout.addLayout(self.horizontalLayout)
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.labelDepthSearch = QtWidgets.QLabel(self.groupBox)
		self.labelDepthSearch.setObjectName("labelDepthSearch")
		self.horizontalLayout_3.addWidget(self.labelDepthSearch)
		spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_3.addItem(spacerItem1)
		self.radioButtonDepthSearchYes = QtWidgets.QRadioButton(self.groupBox)
		self.radioButtonDepthSearchYes.setObjectName("radioButtonDepthSearchYes")
		self.horizontalLayout_3.addWidget(self.radioButtonDepthSearchYes)
		self.radioButtonDepthSearchNo = QtWidgets.QRadioButton(self.groupBox)
		self.radioButtonDepthSearchNo.setChecked(True)
		self.radioButtonDepthSearchNo.setObjectName("radioButtonDepthSearchNo")
		self.horizontalLayout_3.addWidget(self.radioButtonDepthSearchNo)
		self.verticalLayout.addLayout(self.horizontalLayout_3)
		self.verticalLayout_2.addWidget(self.groupBox)
		self.groupBox_2 = QtWidgets.QGroupBox(EvolutionParametersDialog)
		self.groupBox_2.setObjectName("groupBox_2")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_6.setObjectName("horizontalLayout_6")
		self.labelMutator = QtWidgets.QLabel(self.groupBox_2)
		self.labelMutator.setObjectName("labelMutator")
		self.horizontalLayout_6.addWidget(self.labelMutator)
		spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_6.addItem(spacerItem2)
		self.comboBoxMutator = QtWidgets.QComboBox(self.groupBox_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.comboBoxMutator.sizePolicy().hasHeightForWidth())
		self.comboBoxMutator.setSizePolicy(sizePolicy)
		self.comboBoxMutator.setObjectName("comboBoxMutator")
		self.comboBoxMutator.addItem("")
		self.comboBoxMutator.addItem("")
		self.horizontalLayout_6.addWidget(self.comboBoxMutator)
		self.verticalLayout_3.addLayout(self.horizontalLayout_6)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.labelProbability = QtWidgets.QLabel(self.groupBox_2)
		self.labelProbability.setObjectName("labelProbability")
		self.horizontalLayout_2.addWidget(self.labelProbability)
		spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_2.addItem(spacerItem3)
		self.spinBoxProbability = QtWidgets.QSpinBox(self.groupBox_2)
		self.spinBoxProbability.setMaximum(100)
		self.spinBoxProbability.setProperty("value", 10)
		self.spinBoxProbability.setObjectName("spinBoxProbability")
		self.horizontalLayout_2.addWidget(self.spinBoxProbability)
		self.verticalLayout_3.addLayout(self.horizontalLayout_2)
		self.verticalLayout_2.addWidget(self.groupBox_2)
		self.groupBox_3 = QtWidgets.QGroupBox(EvolutionParametersDialog)
		self.groupBox_3.setObjectName("groupBox_3")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.labelElitism = QtWidgets.QLabel(self.groupBox_3)
		self.labelElitism.setObjectName("labelElitism")
		self.horizontalLayout_5.addWidget(self.labelElitism)
		spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_5.addItem(spacerItem4)
		self.spinBoxElitism = QtWidgets.QSpinBox(self.groupBox_3)
		self.spinBoxElitism.setProperty("value", 2)
		self.spinBoxElitism.setObjectName("spinBoxElitism")
		self.horizontalLayout_5.addWidget(self.spinBoxElitism)
		self.verticalLayout_4.addLayout(self.horizontalLayout_5)
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.labelTournamentSize = QtWidgets.QLabel(self.groupBox_3)
		self.labelTournamentSize.setObjectName("labelTournamentSize")
		self.horizontalLayout_4.addWidget(self.labelTournamentSize)
		spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem5)
		self.spinBoxTournamentSize = QtWidgets.QSpinBox(self.groupBox_3)
		self.spinBoxTournamentSize.setMinimum(2)
		self.spinBoxTournamentSize.setProperty("value", 6)
		self.spinBoxTournamentSize.setObjectName("spinBoxTournamentSize")
		self.horizontalLayout_4.addWidget(self.spinBoxTournamentSize)
		self.verticalLayout_4.addLayout(self.horizontalLayout_4)
		self.verticalLayout_2.addWidget(self.groupBox_3)
		self.buttonBox = QtWidgets.QDialogButtonBox(EvolutionParametersDialog)
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
		self.buttonBox.setObjectName("buttonBox")
		self.verticalLayout_2.addWidget(self.buttonBox)

		self.retranslateUi(EvolutionParametersDialog)
		self.buttonBox.accepted.connect(EvolutionParametersDialog.accept)
		self.buttonBox.rejected.connect(EvolutionParametersDialog.reject)
		QtCore.QMetaObject.connectSlotsByName(EvolutionParametersDialog)

	def retranslateUi(self, EvolutionParametersDialog):
		_translate = QtCore.QCoreApplication.translate
		EvolutionParametersDialog.setWindowTitle(_translate("EvolutionParametersDialog", "Evolution Parameters"))
		self.groupBox.setTitle(_translate("EvolutionParametersDialog", "Crossing"))
		self.labelParentCount.setText(_translate("EvolutionParametersDialog", "Number of parents"))
		self.labelDepthSearch.setText(_translate("EvolutionParametersDialog", "Depth-search"))
		self.radioButtonDepthSearchYes.setText(_translate("EvolutionParametersDialog", "Yes"))
		self.radioButtonDepthSearchNo.setText(_translate("EvolutionParametersDialog", "No"))
		self.groupBox_2.setTitle(_translate("EvolutionParametersDialog", "Mutation"))
		self.labelMutator.setText(_translate("EvolutionParametersDialog", "Mutator"))
		self.comboBoxMutator.setItemText(0, _translate("EvolutionParametersDialog", "Displacement"))
		self.comboBoxMutator.setItemText(1, _translate("EvolutionParametersDialog", "Inversion"))
		self.labelProbability.setText(_translate("EvolutionParametersDialog", "Probability (%)"))
		self.groupBox_3.setTitle(_translate("EvolutionParametersDialog", "Selection"))
		self.labelElitism.setText(_translate("EvolutionParametersDialog", "Elitism"))
		self.labelTournamentSize.setText(_translate("EvolutionParametersDialog", "Tournament size"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	EvolutionParametersDialog = QtWidgets.QDialog()
	ui = Ui_EvolutionParametersDialog()
	ui.setupUi(EvolutionParametersDialog)
	EvolutionParametersDialog.show()
	sys.exit(app.exec_())

